// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokedex.Server.Models;

#nullable disable

namespace Pokedex.Server.Migrations
{
    [DbContext(typeof(Pokemondb))]
    partial class PokemondbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pokedex.Server.Models.Pokemon", b =>
                {
                    b.Property<int>("pId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pId"));

                    b.Property<int?>("PokemontrainerTid")
                        .HasColumnType("int");

                    b.Property<string>("abilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pId");

                    b.HasIndex("PokemontrainerTid");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("Pokedex.Server.Models.Pokemontrainer", b =>
                {
                    b.Property<int>("Tid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Tid"));

                    b.Property<string>("Tname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Tid");

                    b.ToTable("PokemonTrainers");
                });

            modelBuilder.Entity("Pokedex.Server.Models.Pokemon", b =>
                {
                    b.HasOne("Pokedex.Server.Models.Pokemontrainer", null)
                        .WithMany("Pokemons")
                        .HasForeignKey("PokemontrainerTid");
                });

            modelBuilder.Entity("Pokedex.Server.Models.Pokemontrainer", b =>
                {
                    b.Navigation("Pokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
